testproject/diary/urls.py
from django.urls import path
from . import views


app_name = "diary"
urlpatterns = [
    path("", views.index, name="index"),
    path("page/create/", views.page_create, name="page_create"),
    path("pages/", views.page_list, name="page_list"),
    path("page/<uuid:id>/", views.page_detail, name="page_detail"),
    path("page/<uuid:id>/update/", views.page_update, name="page_update"),
    path("page/<uuid:id>/putout/", views.page_putout, name="page_putout"),
    path("page/putoutlist", views.page_putoutlist, name="page_putoutlist"),
    path("page/<uuid:id>/delete/", views.page_delete, name="page_delete"),
    path("master_item/", views.master_item, name="master_item"),
    path("master_brand/", views.master_brand, name="master_brand"),
    path("qr/<uuid:id>/", views.QrCreateView.as_view(), name="qr_create"),
    path('page_history/<uuid:pk>/',
         views.PageHistoryView.as_view(), name='page_history'),
]

testproject/testproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("diary/",include("diary.urls")),
    path('accounts/',include('accounts.urls')),
    path('',include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testproject/diary/models.py
from django.db import models
from pathlib import Path
from datetime import datetime
import uuid
from simple_history.models import HistoricalRecords


class ItemMst(models.Model):
    code = models.IntegerField(
        blank=False, null=False, unique=True, verbose_name="品目コード")
    name = models.CharField(blank=False, null=False,
                            max_length=50, verbose_name="品目名称")

    def __str__(self):
        return self.name


class BrandMst(models.Model):
    code = models.IntegerField(
        blank=False, null=False, unique=True, verbose_name="品種コード")
    name = models.CharField(blank=False, null=False,
                            max_length=50, verbose_name="品種名称")
    item = models.ForeignKey(
        ItemMst, on_delete=models.PROTECT, to_field='code', verbose_name="品目コード"
    )

    def __str__(self):
        return self.name


class AreaMst(models.Model):
    code = models.IntegerField(
        blank=False, null=False, unique=True, verbose_name="産地コード")
    name = models.CharField(blank=False, null=False,
                            max_length=20, verbose_name="産地名称")

    def __str__(self):
        return self.name


class HumanMst(models.Model):
    code = models.IntegerField(
        blank=False, null=False, unique=True, verbose_name="担当者コード")
    name = models.CharField(blank=False, null=False,
                            max_length=20, verbose_name="担当者名称")

    def __str__(self):
        return self.name


class QtyUnitMst(models.Model):
    code = models.IntegerField(
        blank=False, null=False, unique=True, verbose_name="数量単位コード")
    name = models.CharField(blank=False, null=False,
                            max_length=10, verbose_name="数量単位名称")

    def __str__(self):
        return self.name


class WtUnitMst(models.Model):
    code = models.IntegerField(
        blank=False, null=False, unique=True, verbose_name="重量単位コード")
    name = models.CharField(blank=False, null=False,
                            max_length=10, verbose_name="重量単位名称")

    def __str__(self):
        return self.name


class SectionMst(models.Model):
    code = models.IntegerField(
        blank=False, null=False, unique=True, verbose_name="部署コード")
    name = models.CharField(blank=False, null=False,
                            max_length=20, verbose_name="部署名称")

    def __str__(self):
        return self.name


class Page(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          editable=False, verbose_name="ID")
    code_item = models.ForeignKey(
        ItemMst, on_delete=models.PROTECT, to_field='code', blank=False, null=False, verbose_name="品目",
    )
    code_item_brand = models.ForeignKey(
        BrandMst, on_delete=models.PROTECT, to_field='code', blank=False, null=False, verbose_name="品種",
        default=0
    )
    code_area = models.ForeignKey(
        AreaMst, on_delete=models.PROTECT, to_field='code', blank=False, null=False, verbose_name="産地",
    )
    code_put_human = models.ForeignKey(
        HumanMst, on_delete=models.PROTECT, to_field='code', blank=False, null=False, verbose_name="担当者",
    )
    area_detail = models.CharField(
        blank=True, null=False, max_length=20, verbose_name="地名")
    put_date = models.DateTimeField(
        blank=False, null=False, default=datetime.now, verbose_name="入庫日時")
    put_qty = models.IntegerField(blank=False, null=False, verbose_name="入庫数")
    put_qty_unit = models.ForeignKey(
        QtyUnitMst, on_delete=models.PROTECT, to_field='code', blank=False, null=False, verbose_name="数量単位"
    )
    put_wt = models.IntegerField(blank=False, null=False, verbose_name="入庫重量")
    put_wt_unit = models.ForeignKey(
        WtUnitMst, on_delete=models.PROTECT, to_field='code', blank=False, null=False, verbose_name="重量単位"
    )
    picture = models.ImageField(
        upload_to="diary/picture/", blank=True, null=True, verbose_name="画像")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="作成日時")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="更新日時")
    history = HistoricalRecords()

    def __str__(self):
        return str(self.code_item)

    def delete(self, *args, **kwargs):
        picture = self.picture
        super().delete(*args, **kwargs)
        if picture:
            Path(picture.path).unlink(missing_ok=True)


class PagePutOut(models.Model):
    page = models.ForeignKey(Page, on_delete=models.CASCADE)
    code_putout_human = models.ForeignKey(
        HumanMst, on_delete=models.PROTECT, to_field='code', verbose_name="出庫担当者"
    )
    putout_date = models.DateTimeField(auto_now_add=True, verbose_name="出庫日時")
    old_put_qty = models.IntegerField(verbose_name="以前の在庫数")
    putout_qty = models.IntegerField(verbose_name="出庫数")
    old_put_wt = models.IntegerField(verbose_name="以前の在庫重量")
    putout_wt = models.IntegerField(verbose_name="出庫重量")
    putout_section = models.ForeignKey(
        SectionMst, on_delete=models.PROTECT, to_field='code', verbose_name="出庫部署"
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="作成日時")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="更新日時")

    def __str__(self):
        return f"{self.page} - {self.putout_date}"

testproject/diary/views.py
from .forms import PagePutOutForm
from django.utils.dateparse import parse_datetime  # これを追加
from .forms import PageForm
from .models import Page
from django.views.generic import ListView
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.views import View
from django.urls import reverse
from .forms import PageForm, ItemMstForm, BrandMstForm, HumanMstForm, QtyUnitMstForm, WtUnitMstForm, AreaMstForm, PagePutOutForm
from .models import Page, ItemMst, BrandMst, HumanMst, QtyUnitMst, WtUnitMst, AreaMst, SectionMst, PagePutOut
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo
# QRcode作成
import qrcode
import qrcode.image.svg
from io import BytesIO
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile


class IndexView(LoginRequiredMixin, View):
    def get(self, request):
        datetime_now = datetime.now(
            ZoneInfo("Asia/Tokyo")
        ).strftime("%Y年%m月%d日 %H時%M分%S秒")
        return render(
            request, "diary/index.html", {"datetime_now": datetime_now})


class PageCreateView(LoginRequiredMixin, View):
    def get(self, request):
        form = PageForm()
        return render(request, "diary/page_form.html", {"form": form})

    def post(self, request):
        form = PageForm(request.POST, request.FILES)
        if form.is_valid():
            page = form.save()  # 保存したオブジェクトを取得

            # QRコード生成ページの絶対URLを取得
            current_site = get_current_site(request)
            qr_url = f"http://{current_site.domain}{reverse('diary:qr_create', kwargs={'id': page.id})}"
            print(f"QR URL (server-side): {qr_url}")  # サーバー側でデバッグ用に確認

            # 新しいタブでQRコードを開くためのJavaScriptを埋め込む
            return render(request, "diary/redirect_with_qr.html", {"qr_url": qr_url})

        return render(request, "diary/page_form.html", {"form": form})


class PageListView(LoginRequiredMixin, View):
    def get(self, request):
        code_item = request.GET.get('code_item', '')
        item = request.GET.get('item', '')
        item_brand = request.GET.get('item_brand', '')
        area = request.GET.get('area', '')
        area_detail = request.GET.get('area_detail', '')
        put_human = request.GET.get('put_human', '')
        start_date = request.GET.get('start_date')
        end_date = request.GET.get('end_date')
        page_list = Page.objects.all()

        if code_item:
            page_list = page_list.filter(code_item__code__icontains=code_item)
        if item:
            page_list = page_list.filter(code_item__name__icontains=item)
        if item_brand:
            page_list = page_list.filter(
                code_item_brand__name__icontains=item_brand)
        if area:
            page_list = page_list.filter(code_area__name__icontains=area)
        if area_detail:
            page_list = page_list.filter(area_detail__icontains=area_detail)
        if put_human:
            page_list = page_list.filter(
                code_put_human__name__icontains=put_human)

        if start_date:
            page_list = page_list.filter(put_date__gte=start_date)
        if end_date:
            end_datetime = datetime.strptime(
                end_date, '%Y-%m-%d') + timedelta(days=1) - timedelta(seconds=1)
            page_list = page_list.filter(put_date__lte=end_datetime)

        context = {
            'page_list': page_list,
            'code_item': code_item,
            'item': item,
            'item_brand': item_brand,
            'area': area,
            'area_detail': area_detail,
            'put_human': put_human,
            'start_date': start_date,
            'end_date': end_date,
        }

        return render(request, "diary/page_list.html", context)


class PageDetailView(LoginRequiredMixin, View):
    def get(self, request, id):
        page = get_object_or_404(Page, id=id)
        return render(request, "diary/page_detail.html", {"page": page})


class PageUpdateView(LoginRequiredMixin, View):
    def get(self, request, id):
        page = get_object_or_404(Page, id=id)
        form = PageForm(instance=page)
        return render(request, "diary/page_update.html", {"form": form, "page": page})

    def post(self, request, id):
        page = get_object_or_404(Page, id=id)
        form = PageForm(request.POST, request.FILES, instance=page)
        if form.is_valid():
            form.save()
            return redirect("diary:page_detail", id=id)
        return render(request, "diary/page_update.html", {"form": form, "page": page})


class PagePutOutView(LoginRequiredMixin, View):
    def get(self, request, id):
        page = get_object_or_404(Page, id=id)
        form = PageForm(instance=page)
        sections = SectionMst.objects.all()
        return render(request, "diary/page_putout.html", {"form": form, "page": page, "sections": sections})

    def post(self, request, id):
        page = get_object_or_404(Page, id=id)
        form = PageForm(request.POST, request.FILES, instance=page)
        putout_form = PagePutOutForm(request.POST)

        subtract_weight = request.POST.get('subtract_weight')
        subtract_quantity = request.POST.get('subtract_quantity')
        put_date_str = request.POST.get('put_date')

        # 日時形式を変換
        put_date = parse_datetime(put_date_str)  # parse_datetime を使って変換
        if put_date is None:
            form.add_error('put_date', 'エラー：日時形式が正しくありません。')
        else:
            page.put_date = put_date

        if subtract_quantity and subtract_quantity.strip():
            try:
                subtract_quantity = float(subtract_quantity)
                if page.put_qty - subtract_quantity <= 0:
                    form.add_error(None, "エラー：出庫数量がマイナスになります。")
            except ValueError:
                form.add_error(None, "エラー：無効な数値が入力されました。")
        else:
            form.add_error(None, "エラー：出庫数量が入力されていません。")

        if subtract_weight and subtract_weight.strip():
            try:
                subtract_weight = float(subtract_weight)
                if page.put_wt - subtract_weight <= 0:
                    form.add_error(None, "エラー：出庫重量がマイナスになります。")
            except ValueError:
                form.add_error(None, "エラー：無効な数値が入力されました。")
        else:
            form.add_error(None, "エラー：出庫重量が入力されていません。")

        if not form.errors and putout_form.is_valid():  # エラーがない場合のみリダイレクト
            page.put_wt -= subtract_weight
            page.put_qty -= subtract_quantity
            page.save()

            putout_section_code = request.POST.get('putout_section')
            putout_section = get_object_or_404(
                SectionMst, code=putout_section_code)

            PagePutOut.objects.create(
                page=page,
                code_putout_human=page.code_put_human,
                old_put_qty=page.put_qty + subtract_quantity,
                putout_qty=subtract_quantity,
                old_put_wt=page.put_wt + subtract_weight,
                putout_wt=subtract_weight,
                putout_section=putout_section
            )

            return redirect('diary:page_list')

        return render(request, "diary/page_putout.html", {"form": form, "page": page, "sections": SectionMst.objects.all()})


class PutOutListView(LoginRequiredMixin, View):
    def get(self, request):
        page_put_outs = PagePutOut.objects.all()
        code_item = request.GET.get('code_item', '')
        item = request.GET.get('item', '')
        item_brand = request.GET.get('item_brand', '')
        area = request.GET.get('area', '')
        area_detail = request.GET.get('area_detail', '')
        putout_human = request.GET.get('putout_human', '')
        start_date = request.GET.get('start_date')
        end_date = request.GET.get('end_date')

        if code_item:
            page_put_outs = page_put_outs.filter(
                page__code_item__code__icontains=code_item)
        if item:
            page_put_outs = page_put_outs.filter(
                page__code_item__name__icontains=item)
        if item_brand:
            page_put_outs = page_put_outs.filter(
                page__code_item_brand__name__icontains=item_brand)
        if area:
            page_put_outs = page_put_outs.filter(
                page__code_area__name__icontains=area)
        if area_detail:
            page_put_outs = page_put_outs.filter(
                page__area_detail__icontains=area_detail)
        if putout_human:
            page_put_outs = page_put_outs.filter(
                code_putout_human__name__icontains=putout_human)

        if start_date:
            page_put_outs = page_put_outs.filter(putout_date__gte=start_date)
        if end_date:
            end_datetime = datetime.strptime(
                end_date, '%Y-%m-%d') + timedelta(days=1) - timedelta(seconds=1)
            page_put_outs = page_put_outs.filter(putout_date__lte=end_datetime)

        context = {
            'page_put_outs': page_put_outs,
            'code_item': code_item,
            'item': item,
            'item_brand': item_brand,
            'area': area,
            'area_detail': area_detail,
            'putout_human': putout_human,
            'start_date': start_date,
            'end_date': end_date,
        }
        return render(request, "diary/page_putoutlist.html", context)


class PageDeleteView(LoginRequiredMixin, View):
    def get(self, request, id):
        page = get_object_or_404(Page, id=id)
        return render(request, "diary/page_confirm_delete.html", {"page": page})

    def post(self, request, id):
        page = get_object_or_404(Page, id=id)
        page.delete()
        return redirect('diary:page_list')


class MasterItemView(LoginRequiredMixin, View):
    def get(self, request):
        form = ItemMstForm()
        mst = ItemMst.objects.all()

testproject/diary/templates/diary/index.html
{% extends "base/diary_base.html" %}
{% block body %}

<ul>
    <a href="{% url 'diary:page_create' %}">
        <div class="c-btn slide">入庫入力</div>
    </a>
    <a href="{% url 'diary:page_list' %}">
        <div class="c-btn slide">在庫一覧</div>
    </a>
    <a href="{% url 'diary:page_putoutlist' %}">
        <div class="c-btn slide">出庫一覧</div>
    </a>
</ul>
<ul>
    <a href="{% url 'diary:master_item' %}">
        <div class="c-btn slide">品目マスタ</div>
    </a>
    <a href="{% url 'diary:master_brand' %}">
        <div class="c-btn slide">品種マスタ</div>
    </a>
</ul>

{% endblock %}

testproject/diary/templates/diary/master_brand.html
{% extends "base/diary_base.html" %}
{% block body %}

<h2>品目マスタ追加</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %} <!-- セキュリティ必要な記述らしい -->
    {{ form.as_p }}
    <button type="submit">保存</button>
</form>
<br>

<table class="list-form">
  <tr>
    <th>品目</th>
    <th>品目コード</th>
   </tr>
  
  {% for item in itemmst %}
  <tr>
    <td>{{ item.code }}</td>
    <td>{{ item.name }}</td>
  </tr>
  {% empty %}
  <div>マスタがないよ</div>
  {% endfor %}
</table>

<div class="bottom-fix">
  <a href="{% url 'diary:index' %}" class="white">戻る</a>
</div>

{% endblock %}

testproject/diary/templates/diary/master_item.html
{% extends "base/diary_base.html" %}
{% block body %}

<h2>品目マスタ追加</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %} <!-- セキュリティ必要な記述らしい -->
    {{ form.as_p }}
    <button type="submit">保存</button>
</form>
<br>

<table class="list-form">
  <tr>
    <th>品目</th>
    <th>品目コード</th>
  </tr>
  
  {% for item in mst %}
  <tr>
    <td>{{ item.code }}</td>
    <td>{{ item.name }}</td>
  </tr>
  {% empty %}
  <div>マスタがないよ</div>
  {% endfor %}
</table>

<div class="bottom-fix">
  <a href="{% url 'diary:index' %}" class="white">戻る</a>
</div>

{% endblock %}

testproject/diary/templates/diary/page_confirm_delete.html
{% extends "base/diary_base.html" %}
{% block body %}

<form method="POST">
    {% csrf_token %}
    <p>このデータを消すよ？</p>
    <button type="submit">削除</button>
</form>
<table>
    <tr>
      <th>品目</th>
      <td>{{ page.code_item }}</td>
    </tr>
    <tr>
      <th>品種</th>
      <td>{{ page.code_item_brand }}</td>
    </tr>
    <tr>
      <th>産地</th>
      <td>{{ page.code_area }}</td>
    </tr>
    <tr>
      <th>担当者</th>
      <td>{{ page.code_put_human }}</td>
    </tr>
    <tr>
      <th>地名</th>
      <td>{{ page.area_detail }}</td>
    </tr>
    <tr>
      <th>入庫日時</th>
      <td>{{ page.put_date }}</td>
    </tr>
    <tr>
      <th>入庫数</th>
      <td>{{ page.put_qty }}</td>
      <td>{{ page.put_qty_unit }}</td>
    </tr>
    <tr>
      <th>入庫重量</th>
      <td>{{ page.put_wt }}</td>
      <td>{{ page.put_wt_unit }}</td>
    </tr>
    <tr>
      <th>更新日時</th>
      <td>{{ page.updated_at }}</td>
    </tr>
  </table>
{% if page.picture %}
    <img src="{{ page.picture.url }}">
{% endif %}

{% endblock %}

testproject/diary/templates/diary/page_detail.html
{% extends "base/diary_base.html" %}
{% block body %}

<style>
  .list-form label {
    width: 100px; /* ラベルの固定幅を設定 */
    font-weight: bold;
    margin: 0px 20px;
  }
</style>

<h2>詳細表示</h2>
<table>
  <tr>
    <th>品目</th>
    <td>{{ page.code_item }}</td>
  </tr>
  <tr>
    <th>品種</th>
    <td>{{ page.code_item_brand }}</td>
  </tr>
  <tr>
    <th>産地</th>
    <td>{{ page.code_area }}</td>
  </tr>
  <tr>
    <th>担当者</th>
    <td>{{ page.code_put_human }}</td>
  </tr>
  <tr>
    <th>地名</th>
    <td>{{ page.area_detail }}</td>
  </tr>
  <tr>
    <th>入庫日時</th>
    <td>{{ page.put_date }}</td>
  </tr>
  <tr>
    <th>入庫数</th>
    <td>{{ page.put_qty }}</td>
    <td>{{ page.put_qty_unit }}</td>
  </tr>
  <tr>
    <th>入庫重量</th>
    <td>{{ page.put_wt }}</td>
    <td>{{ page.put_wt_unit }}</td>
  </tr>
  <tr>
    <th>更新日時</th>
    <td>{{ page.updated_at }}</td>
  </tr>
</table>

<dib>{{ page.body | linebreaksbr }}</dib>
{% if page.picture %}
    <img src="{{ page.picture.url }}">
{% endif %}
<br>

<div class="bottom-fix">
  <a href="{% url 'diary:page_list' %}" class="white">戻る</a>
  <a href="{% url 'diary:page_update' page.id %}" class="white">編集</a>
  <a href="{% url 'diary:page_history' page.id %}" class="white">履歴</a>
  <a href="{% url 'diary:page_delete' page.id %}" class="white">削除</a>
</div>


{% endblock %}

testproject/diary/templates/diary/page_form.html
{% extends "base/diary_base.html" %}
{% block body %}

<h2>入庫入力</h2>

<form method="POST" enctype="multipart/form-data" class="input-form">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_code_item" class="label-form">品目</label>
        {{ form.code_item }}
    </div>
    <div class="form-group">
        <label for="id_code_item_brand" class="label-form">品種</label>
        {{ form.code_item_brand }}
    </div>
    <div class="form-group">
        <label for="id_code_area" class="label-form">産地</label>
        {{ form.code_area }}
    </div>
    <div class="form-group">
        <label for="id_code_put_human" class="label-form">担当者</label>
        {{ form.code_put_human }}
    </div>
    <div class="form-group">
        <label for="id_area_detail" class="label-form">地名</label>
        {{ form.area_detail }}
    </div>
    <div class="form-group">
        <label for="id_put_date" class="label-form">入庫日時</label>
        {{ form.put_date }}
    </div>
    <div class="form-group">
        <label for="id_put_qty" class="label-form">入庫数</label>
        {{ form.put_qty }}
    </div>
    <div class="form-group">
        <label for="id_put_qty_unit" class="label-form">数量単位</label>
        {{ form.put_qty_unit }}
    </div>
    <div class="form-group">
        <label for="id_put_wt" class="label-form">入庫重量</label>
        {{ form.put_wt }}
    </div>
    <div class="form-group">
        <label for="id_put_wt_unit" class="label-form">重量単位</label>
        {{ form.put_wt_unit }}
    </div>
    <div class="form-group">
        <label for="id_picture" class="label-form">画像</label>
        {{ form.picture }}
    </div>
    <button type="submit" class="button-form">保存</button>
</form>
<br>

<div class="bottom-fix">
    <a href="{% url 'diary:index' %}" class="white">戻る</a>
</div>

{% endblock %}

testproject/diary/templates/diary/page_putout.html
{% extends "base/diary_base.html" %}
{% block body %}

<h2>出庫処理</h2>

<form method="POST" enctype="multipart/form-data" class="input-form">
    {% csrf_token %}
    <div>
        {{ form.non_field_errors }}  <!-- 非フィールドエラーメッセージを表示 -->
        <label for="id_code_item" class="label-form">品目</label>
        <div class="input-form">{{ page.code_item }}</div>
        <input type="hidden" name="code_item" value="{{ page.code_item.code }}">

        <label for="id_code_item_brand" class="label-form">品種</label>
        <div class="input-form">{{ page.code_item_brand }}</div>
        <input type="hidden" name="code_item_brand" value="{{ page.code_item_brand.code }}">

        <label for="id_code_area" class="label-form">産地</label>
        <div class="input-form">{{ page.code_area }}</div>
        <input type="hidden" name="code_area" value="{{ page.code_area.code }}">

        <label for="id_code_put_human" class="label-form">担当者</label>
        <div class="input-form">{{ page.code_put_human }}</div>
        <input type="hidden" name="code_put_human" value="{{ page.code_put_human.code }}">

        <label for="id_put_date" class="label-form">入庫日時</label>
        <input type="datetime-local" id="id_put_date" name="put_date"
        value="{{ page.put_date|date:'Y-m-d\\TH:i' }}" class="input-form">

        <label class="label-form">現在の数量</label>
        <div class="input-form">{{ page.put_qty }}{{ page.put_qty_unit }}</div>
        <input type="hidden" name="put_qty" value="{{ page.put_qty }}">
        <input type="hidden" name="put_qty_unit" value="{{ page.put_qty_unit.code }}">

        <label class="label-form">出庫数量</label>
        <input type="number" name="subtract_quantity" class="input-form" id="id_subtract_qty_value">
        {{ form.subtract_quantity.errors }}

        <label class="label-form">現在の重量</label>
        <div class="input-form">{{ page.put_wt }}{{ page.put_wt_unit }}</div>
        <input type="hidden" name="put_wt" value="{{ page.put_wt }}">
        <input type="hidden" name="put_wt_unit" value="{{ page.put_wt_unit.code }}">

        <label class="label-form">出庫重量</label>
        <input type="number" name="subtract_weight" class="input-form" id="id_subtract_wt_value">
        {{ form.subtract_weight.errors }}

        <label for="id_putout_section" class="label-form">出庫部署</label>
        <select name="putout_section" id="id_putout_section" class="input-form" required>
            <option value="" disabled selected>選択してください</option>
            {% for section in sections %}
                <option value="{{ section.code }}">{{ section.name }}</option>
            {% endfor %}
        </select>

        <label for="id_picture" class="label-form">画像</label>
        <div class="input-form">{{ page.picture }}</div>

    </div>
    <br>
    <button type="submit">更新</button>
</form>

<div class="bottom-fix">
    <a href="{% url 'diary:page_list' %}" class="white">戻る</a>
</div>

{% endblock %}

testproject/diary/templates/diary/page_update.html
{% extends "base/diary_base.html" %}
{% block body %}

<h2>在庫変更</h2>

<form method="POST" enctype="multipart/form-data" class="input-form">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_code_item">品目</label>
        {{ form.code_item }}
    </div>
    <div class="form-group">
        <label for="id_code_item_brand">品種</label>
        {{ form.code_item_brand }}
    </div>
    <div class="form-group">
        <label for="id_code_area">産地</label>
        {{ form.code_area }}
    </div>
    <div class="form-group">
        <label for="id_code_put_human">担当者</label>
        {{ form.code_put_human }}
    </div>
    <div class="form-group">
        <label for="id_area_detail">地名</label>
        {{ form.area_detail }}
    </div>
    <div class="form-group">
        <label for="id_put_date">入庫日時</label>
        {{ form.put_date }}
    </div>
    <div class="form-group">
        <label for="id_put_qty">入庫数</label>
        {{ form.put_qty }}
    </div>
    <div class="form-group">
        <label for="id_put_qty_unit">数量単位</label>
        {{ form.put_qty_unit }}
    </div>
    <div class="form-group">
        <label for="id_put_wt">入庫重量</label>
        {{ form.put_wt }}
    </div>
    <div class="form-group">
        <label for="id_put_wt_unit">重量単位</label>
        {{ form.put_wt_unit }}
    </div>
    <div class="form-group">
        <label for="id_picture">画像</label>
        {{ form.picture }}
    </div>
    <button type="submit">更新</button>
</form>
<br>

<h2 class="link-container">
    <a href="{% url 'diary:page_detail' page.id %}">戻る</a>
</h2>
  
{% endblock %}

testproject/diary/templates/diary/redirect_with_qr.html
<!DOCTYPE html>
<html>
<head>
    <title>Redirecting...</title>
    <p>QR URL: {{ qr_url }}</p>
    <script>
        console.log("QR URL:", "{{ qr_url }}");  // デバッグ用ログ
        window.open("{{ qr_url }}", "_blank");
        window.location.href = "{% url 'diary:index' %}";
    </script>
</head>
<body>
    <p>リダイレクト中...</p>
</body>
</html>